language: python
python: "3.9"
sudo: true
before_script:
    - sudo apt-get install python-fuse python3-pip python3-dev libffi-dev libgit2-dev cmake -y
    - wget https://github.com/libgit2/libgit2/archive/v1.1.0.tar.gz
    - tar xzf v1.1.0.tar.gz
    - cd libgit2-1.1.0/
    - cmake .
    - make
    - sudo make install
    - cd ..
    - sudo ldconfig
    - python3 setup.py install
script: 
    - make test
